### PR TITLE
Fix quoted and escaped whitespace for label and env directives

### LINKED ISSUE #27: Label Is Invalid when spaces in label
When the label value contains spaces, the "Label Is Invalid" check breaks down:

    File:   <stdin>
    Issues: 1
    Line 41: LABEL build_user_on_behalf_of="Sander\ Verhagen"
    Issue  Category      Title                 Description
        1  Possible Bug  Label Is Invalid      Using LABEL should be in key=value format.

### PR DESCRIPTION
**Pull request by emosbaugh**
resolves #27

### CODE REVIEW

File: test/parser.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+    });
+
+    it("honor escape characters", function(){
+      expect(parser.words("one two\\ thre\\e \"fou\\r\"")).to.have.length(3)
+        .and.to.eql(['one', 'two\\ thre\\e', '"fou\\r"']);
+    });
+
+    it("ignore escape character at line end", function(){
+      expect(parser.words("one two\\")).to.have.length(2)
+        .and.to.eql(['one', 'two']);
```
Comment (divolgin) [inline test/parser.js]: Shouldn't this match `'two\'`

File: test/parser.js [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+      expect(parser.words("one \"two\\")).to.have.length(2)
+        .and.to.eql(['one', '\"two']);
```
Comment (divolgin) [inline test/parser.js]: Shouldn't this match `"two\`

File: lib/parser.js [hunk 3]
```diff
@@ -0,0 +1,113 @@
+// ported from github.com/docker/docker
+// https://github.com/docker/docker/blob/e95b6b51daed868094c7b66113381d5088e831b4/builder/dockerfile/parser/line_parsers.go
+
+var parser = module.exports = {
```
Comment (divolgin) [inline lib/parser.js]: I'm going to have to trust you on this one.  It would be easier to check if you used a tokenizer.
